// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type OutboxEvent struct {
	ID            uuid.UUID       `json:"id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	Status        sql.NullString  `json:"status"`
	CreatedAt     sql.NullTime    `json:"created_at"`
}

type User struct {
	ID            uuid.UUID      `json:"id"`
	Email         string         `json:"email"`
	PasswordHash  string         `json:"password_hash"`
	Name          sql.NullString `json:"name"`
	Role          string         `json:"role"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	PhoneNumber   sql.NullString `json:"phone_number"`
	PhoneVerified sql.NullBool   `json:"phone_verified"`
}
