// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type OutboxEvent struct {
	ID            uuid.UUID       `json:"id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	Status        sql.NullString  `json:"status"`
	CreatedAt     sql.NullTime    `json:"created_at"`
}

type Trip struct {
	ID             uuid.UUID       `json:"id"`
	PassengerID    uuid.UUID       `json:"passenger_id"`
	DriverID       uuid.NullUUID   `json:"driver_id"`
	Status         string          `json:"status"`
	SourceLat      float64         `json:"source_lat"`
	SourceLng      float64         `json:"source_lng"`
	DestLat        float64         `json:"dest_lat"`
	DestLng        float64         `json:"dest_lng"`
	EstimatedPrice float64         `json:"estimated_price"`
	FinalPrice     sql.NullFloat64 `json:"final_price"`
	CreatedAt      sql.NullTime    `json:"created_at"`
	AcceptedAt     sql.NullTime    `json:"accepted_at"`
	CompletedAt    sql.NullTime    `json:"completed_at"`
}
