// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const acceptTrip = `-- name: AcceptTrip :exec
UPDATE trips
SET driver_id = $2, status = $3, accepted_at = NOW()
WHERE id = $1
`

type AcceptTripParams struct {
	ID       uuid.UUID     `json:"id"`
	DriverID uuid.NullUUID `json:"driver_id"`
	Status   string        `json:"status"`
}

func (q *Queries) AcceptTrip(ctx context.Context, arg AcceptTripParams) error {
	_, err := q.db.ExecContext(ctx, acceptTrip, arg.ID, arg.DriverID, arg.Status)
	return err
}

const completeTrip = `-- name: CompleteTrip :exec
UPDATE trips
SET status = $2, final_price = $3, completed_at = NOW()
WHERE id = $1
`

type CompleteTripParams struct {
	ID         uuid.UUID       `json:"id"`
	Status     string          `json:"status"`
	FinalPrice sql.NullFloat64 `json:"final_price"`
}

func (q *Queries) CompleteTrip(ctx context.Context, arg CompleteTripParams) error {
	_, err := q.db.ExecContext(ctx, completeTrip, arg.ID, arg.Status, arg.FinalPrice)
	return err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (id, aggregate_type, aggregate_id, event_type, payload, status, created_at, correlation_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateOutboxEventParams struct {
	ID            uuid.UUID       `json:"id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   uuid.UUID       `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	Status        sql.NullString  `json:"status"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	CorrelationID sql.NullString  `json:"correlation_id"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.ExecContext(ctx, createOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Status,
		arg.CreatedAt,
		arg.CorrelationID,
	)
	return err
}

const createTrip = `-- name: CreateTrip :exec
INSERT INTO trips (
    id, passenger_id, driver_id, status, 
    source_lat, source_lng, dest_lat, dest_lng, 
    estimated_price, currency, source_address, dest_address, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateTripParams struct {
	ID             uuid.UUID      `json:"id"`
	PassengerID    uuid.UUID      `json:"passenger_id"`
	DriverID       uuid.NullUUID  `json:"driver_id"`
	Status         string         `json:"status"`
	SourceLat      float64        `json:"source_lat"`
	SourceLng      float64        `json:"source_lng"`
	DestLat        float64        `json:"dest_lat"`
	DestLng        float64        `json:"dest_lng"`
	EstimatedPrice float64        `json:"estimated_price"`
	Currency       sql.NullString `json:"currency"`
	SourceAddress  sql.NullString `json:"source_address"`
	DestAddress    sql.NullString `json:"dest_address"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) error {
	_, err := q.db.ExecContext(ctx, createTrip,
		arg.ID,
		arg.PassengerID,
		arg.DriverID,
		arg.Status,
		arg.SourceLat,
		arg.SourceLng,
		arg.DestLat,
		arg.DestLng,
		arg.EstimatedPrice,
		arg.Currency,
		arg.SourceAddress,
		arg.DestAddress,
		arg.CreatedAt,
	)
	return err
}

const getStuckTrips = `-- name: GetStuckTrips :many
SELECT id, passenger_id, driver_id, status, source_lat, source_lng, dest_lat, dest_lng, estimated_price, final_price, created_at, accepted_at, completed_at, currency, source_address, dest_address FROM trips 
WHERE status = 'REQUESTED' AND created_at < $1
`

func (q *Queries) GetStuckTrips(ctx context.Context, createdAt sql.NullTime) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, getStuckTrips, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.PassengerID,
			&i.DriverID,
			&i.Status,
			&i.SourceLat,
			&i.SourceLng,
			&i.DestLat,
			&i.DestLng,
			&i.EstimatedPrice,
			&i.FinalPrice,
			&i.CreatedAt,
			&i.AcceptedAt,
			&i.CompletedAt,
			&i.Currency,
			&i.SourceAddress,
			&i.DestAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrip = `-- name: GetTrip :one
SELECT id, passenger_id, driver_id, status, source_lat, source_lng, dest_lat, dest_lng, estimated_price, final_price, created_at, accepted_at, completed_at, currency, source_address, dest_address FROM trips WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTrip(ctx context.Context, id uuid.UUID) (Trip, error) {
	row := q.db.QueryRowContext(ctx, getTrip, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.PassengerID,
		&i.DriverID,
		&i.Status,
		&i.SourceLat,
		&i.SourceLng,
		&i.DestLat,
		&i.DestLng,
		&i.EstimatedPrice,
		&i.FinalPrice,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.CompletedAt,
		&i.Currency,
		&i.SourceAddress,
		&i.DestAddress,
	)
	return i, err
}

const getUnpublishedEvents = `-- name: GetUnpublishedEvents :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, status, created_at, correlation_id FROM outbox_events 
WHERE (status = 'PENDING' OR status = 'FAILED') 
ORDER BY created_at ASC 
LIMIT $1::int
`

func (q *Queries) GetUnpublishedEvents(ctx context.Context, dollar_1 int32) ([]OutboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, getUnpublishedEvents, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.CorrelationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isEventProcessed = `-- name: IsEventProcessed :one
SELECT EXISTS(SELECT 1 FROM inbox_events WHERE id = $1)
`

func (q *Queries) IsEventProcessed(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, isEventProcessed, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
INSERT INTO inbox_events (id, event_type) VALUES ($1, $2)
`

type MarkEventProcessedParams struct {
	ID        uuid.UUID `json:"id"`
	EventType string    `json:"event_type"`
}

func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error {
	_, err := q.db.ExecContext(ctx, markEventProcessed, arg.ID, arg.EventType)
	return err
}

const updateEventStatus = `-- name: UpdateEventStatus :exec

UPDATE outbox_events 
SET status = $1 
WHERE id = $2
`

type UpdateEventStatusParams struct {
	Status sql.NullString `json:"status"`
	ID     uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEventStatus, arg.Status, arg.ID)
	return err
}

const updateTripDriver = `-- name: UpdateTripDriver :exec
UPDATE trips 
SET driver_id = $2
WHERE id = $1
`

type UpdateTripDriverParams struct {
	ID       uuid.UUID     `json:"id"`
	DriverID uuid.NullUUID `json:"driver_id"`
}

func (q *Queries) UpdateTripDriver(ctx context.Context, arg UpdateTripDriverParams) error {
	_, err := q.db.ExecContext(ctx, updateTripDriver, arg.ID, arg.DriverID)
	return err
}

const updateTripStatus = `-- name: UpdateTripStatus :exec
UPDATE trips 
SET status = $2
WHERE id = $1
`

type UpdateTripStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTripStatus, arg.ID, arg.Status)
	return err
}
